# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reviewPJ2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON', '~> 4.0'

  pod 'Alamofire', '~> 5.5'

  pod "SwiftSpinner"

  pod "PromiseKit", "~> 6.8"
  
  pod 'RealmSwift', '4.4.0'
  
  # Pods for reviewPJ2

end
